In [4]:
import numpy as np

In [3]:
import numpy as np

print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [6]:
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
import numpy as np
ar = np.array([[2, 2, 3],[4, 3, 6]])
mem_size_byte = ar.nbytes
print(mem_size_byte)

48


In [11]:
import numpy as np
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [12]:
import numpy as np
null_vec = np.zeros(10)
null_vec[4] =1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
import numpy as np
vec = np.arange(10,50)
print(vec)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
import numpy as np
vec = np.array([3, 4, 6, 7])
reverse_vec = vec[::-1]
print(reverse_vec)

[7 6 4 3]


In [20]:
import numpy as np
arr = np.arange(9)
mat = arr.reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
import numpy as np
array1 = np.array([1, 2, 0, 0, 4, 0])
nonZero_indices = np.nonzero(array1)
print(nonZero_indices)

(array([0, 1, 4]),)


In [32]:
import numpy as np
iden_mat = np.eye(3)
print(iden_mat)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
